version: "3"

services:
  nginx:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    restart: always

  tasks:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    restart: always
    command: /bin/sh -c "APP_SCOPE=tasks ./docker-entrypoint.sh"
